{{- if .Values.ambassadorConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "ambassador.fullname" . }}-file-config'
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    {{- include "ambassador.labels" . | nindent 4 }}
data:
  ambassadorConfig: |-
    {{- .Values.ambassadorConfig | nindent 4 }}
{{- end }}
